# Default values for contrast-vulnerable-services.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

workshopBaseUrl: "workshop.contrastdemo.com"

# Node name for dedicated node assignment (set by workshop-deployer)
nodeName: ""

mysql:
  # Uses a pull-through cache rule in ECR to pull the official MySQL image from Docker Hub
  # NOTE: This only works in eu-west-1 region for now
  # TODO: Implement the ECR pull-through-cache rules in other regions
  image: 771960604435.dkr.ecr.eu-west-1.amazonaws.com/dockerhub-images/library/mysql:9
  rootPassword: cargocats
  database: db
  user: cargocats
  password: cargocats

cargocatsDataservice:
  image: 771960604435.dkr.ecr.eu-west-1.amazonaws.com/workshop-images/dataservice:v1.1 
  name: dataservice
  agentType: java

frontgateservice:
  image: 771960604435.dkr.ecr.eu-west-1.amazonaws.com/workshop-images/frontgateservice:v1
  name: frontgateservice
  agentType: java   #java

webhookservice:
  image: 771960604435.dkr.ecr.eu-west-1.amazonaws.com/workshop-images/webhookservice:v1 
  name: webhookservice
  agentType: python

imageservice:
  image: 771960604435.dkr.ecr.eu-west-1.amazonaws.com/workshop-images/imageservice:v1
  name: imageservice
  agentType: dotnet-core

labelservice:
  image: 771960604435.dkr.ecr.eu-west-1.amazonaws.com/workshop-images/labelservice:v1
  name: labelservice
  agentType: nodejs

docservice:
  image: 771960604435.dkr.ecr.eu-west-1.amazonaws.com/workshop-images/docservice:v1
  name: docservice
  agentType: python   #python
