# Default values for simulation-console.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

workshopBaseUrl: "work.contrastdemo.com"

# Node name for dedicated node assignment (set by workshop-deployer)
nodeName: ""

zapproxy:
  image: ghcr.io/zaproxy/zaproxy:stable
  name: zapproxy

consoleui:
  image: 771960604435.dkr.ecr.eu-west-1.amazonaws.com/workshop-images/console-ui:v1.1
  name: console-ui
  contrastApiToken: "default-token"
  contrastUniqName: "default"
  contrastApiKey: "default-api-key"
  contrastApiAuthorization: "default-authorization"
  workshopTld: "work.contrastdemo.com"

exploitserver:
  image: 771960604435.dkr.ecr.eu-west-1.amazonaws.com/workshop-images/exploit-server:v1
  name: exploit-server

contrastdatacollector:
  image: 771960604435.dkr.ecr.eu-west-1.amazonaws.com/workshop-images/contrastdatacollector:v1
  name: contrastdatacollector
  contrastUniqName: "default"
  contrastApiToken: "default-token"
  contrastApiKey: "default-api-key"
  contrastApiAuthorization: "default-authorization"
