---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{.Release.Name}}-{{ .Values.cargocatsDataservice.name }}'
  namespace: {{ .Release.Namespace }}
  labels:
    contrast-agent: {{ .Values.cargocatsDataservice.agentType }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.cargocatsDataservice.name }}
  replicas: 1
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: {{ .Values.cargocatsDataservice.name }}
    spec:
{{- if .Values.nodeName }}
      nodeName: {{ .Values.nodeName }}
{{- end }}
      containers:
        - name: {{ .Values.cargocatsDataservice.name }}
          image: {{ .Values.cargocatsDataservice.image }} 
          imagePullPolicy: IfNotPresent
          env:
          - name: CONTRAST__APPLICATION__NAME
            value: '{{ .Values.contrast.uniqName }}-{{.Release.Name}}-{{ .Values.cargocatsDataservice.name }}'
          - name: CONTRAST__SERVER__NAME
            value: '{{ .Values.contrast.uniqName }}-{{.Release.Name}}-{{ .Values.cargocatsDataservice.name }}-agent'
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              memory: "700Mi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "1Gi"
              cpu: "1000m"
              ephemeral-storage: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cargocatsDataservice.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.cargocatsDataservice.name }}
  ports:
    - name: http-port      
      protocol: TCP
      port: 8080           
      targetPort: 8080
---
