---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{.Release.Name}}-{{ .Values.cargocatsDataservice.name }}'
  namespace: {{ .Release.Namespace }}
  labels:
    contrast-agent: flex
spec:
  selector:
    matchLabels:
      app: {{ .Values.cargocatsDataservice.name }}
  replicas: 1
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: {{ .Values.cargocatsDataservice.name }}
    spec:
      containers:
        - name: {{ .Values.cargocatsDataservice.name }}
          image: {{ .Values.cargocatsDataservice.image }} 
          imagePullPolicy: Never
          env:
          - name: CONTRAST__APPLICATION__NAME
            value: '{{ .Values.contrast.uniqName }}-{{.Release.Name}}-{{ .Values.cargocatsDataservice.name }}'
          - name: CONTRAST__SERVER__NAME
            value: '{{ .Values.contrast.uniqName }}-{{.Release.Name}}-{{ .Values.cargocatsDataservice.name }}-agent'
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "2Gi"
              cpu: "1000m"
              ephemeral-storage: "2Gi"

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cargocatsDataservice.name }}
  namespace: default
spec:
  selector:
    app: {{ .Values.cargocatsDataservice.name }}
  ports:
    - name: http-port      
      protocol: TCP
      port: 8080           
      targetPort: 8080     


---
